version: '3.7'

services:
  coordinator:
    container_name: mn-coordinator
    image: 'trinodb/trino:408'
    ports:
      - "9091:8080"
    volumes:
      - ./etc/coordinator:/etc/trino
    networks:
      - trino-multinode-network
  worker1:
    container_name: mn-worker1
    image: 'trinodb/trino:408'
    ports:
      - "8081:8081"
    volumes:
      - ./etc/worker:/etc/trino
    networks:
      - trino-multinode-network
  worker2:
    container_name: mn-worker2
    image: 'trinodb/trino:408'
    ports:
      - "8082:8081"
    volumes:
      - ./etc/worker:/etc/trino
    networks:
      - trino-multinode-network
  worker3:
    container_name: mn-worker3
    image: 'trinodb/trino:408'
    ports:
      - "8083:8081"
    volumes:
      - ./etc/worker:/etc/trino
    networks:
      - trino-multinode-network
  mysql:
    container_name: mn-mysql
    image: mysql:latest
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'
    networks:
      - trino-multinode-network
  mongodb:
    container_name: mn-mongo
    image: 'mongo:latest'
    hostname: mongodb
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - trino-multinode-network
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:10.5.8
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-multinode-network
  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-multinode-network
  minio:
    restart: always
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - trino-multinode-network
    command: server /data --console-address ':9001' --address ':9000'
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data:/data

volumes:
  minio-data:
    driver: local

networks:
  trino-multinode-network:
    driver: bridge
